import {useEffect,useState} from 'react';
import {GameState,createInitialState,BOARD_SIZE,CORNERS,getValidMoves,movePiece} from './gameLogic';
import {getAIMove} from './ai';
export default function App(){
 const [state,setState]=useState<GameState>(createInitialState()),[side,setSide]=useState<'attacker'|'defender'>('defender'),[started,setStarted]=useState(false),[difficulty,setDifficulty]=useState<'beginner'|'easy'|'normal'|'hard'|'expert'>('normal'),[thinking,setThinking]=useState(false),[selected,setSelected]=useState<{x:number;y:number}|null>(null);
 useEffect(()=>{if(!started||state.winner||state.currentPlayer===side)return;setThinking(true);const id=window.setTimeout(()=>{const m=getAIMove(state,difficulty);if(m)setState(s=>movePiece(s,m.fromX,m.fromY,m.toX,m.toY));setThinking(false);},300);return()=>window.clearTimeout(id)},[started,state,side,difficulty]);
 const reset=()=>{setState(createInitialState());setSelected(null);setStarted(true)};
 const click=(x:number,y:number)=>{if(!started||thinking||state.winner||state.currentPlayer!==side)return;const p=state.board[y][x];if(selected){if(getValidMoves(state,selected.x,selected.y).some(m=>m.x===x&&m.y===y)){setState(movePiece(state,selected.x,selected.y,x,y));setSelected(null);return;}if((side==='attacker'&&p==='attacker')||(side==='defender'&&(p==='defender'||p==='king')))setSelected({x,y});else setSelected(null);}else if((side==='attacker'&&p==='attacker')||(side==='defender'&&(p==='defender'||p==='king')))setSelected({x,y});};
 if(!started)return <main className="min-h-screen p-8 bg-slate-900 text-white flex items-center justify-center"><section className="max-w-md w-full space-y-6"><h1 className="text-4xl font-bold">ネファタフル</h1><p>Hnefatafl 11×11 — Néstor Games版</p><div className="flex gap-2"><button className="p-3 bg-red-700 rounded" onClick={()=>setSide('attacker')}>攻撃側</button><button className="p-3 bg-blue-700 rounded" onClick={()=>setSide('defender')}>防御側</button></div><select className="p-3 text-black" value={difficulty} onChange={e=>setDifficulty(e.target.value as typeof difficulty)}>{['beginner','easy','normal','hard','expert'].map(d=><option key={d}>{d}</option>)}</select><button className="block w-full p-4 bg-purple-600 rounded font-bold" onClick={reset}>ゲーム開始</button></section></main>;
 return <main className="min-h-screen bg-slate-900 text-white flex flex-col items-center gap-4 p-4"><h1 className="text-3xl font-bold">ネファタフル</h1><p>{thinking?'AI思考中…':state.message}</p><div className="grid grid-cols-11 border-2 border-amber-900">{state.board.map((row,y)=>row.map((p,x)=>{const valid=selected&&getValidMoves(state,selected.x,selected.y).some(m=>m.x===x&&m.y===y);const cls= p==='king'?'bg-yellow-400':p==='attacker'?'bg-red-600':p==='defender'?'bg-blue-600':CORNERS.some(c=>c.x===x&&c.y===y)?'bg-amber-300/30':x===5&&y===5?'bg-purple-500/30':'bg-amber-100';return <button key={x+','+y} onClick={()=>click(x,y)} className={`w-8 h-8 sm:w-10 sm:h-10 border border-amber-900 ${cls} ${valid?'ring-2 ring-green-400':''}`}>{p==='king'?'♔':p==='attacker'?'A':p==='defender'?'D':''}</button>}))}</div><button className="p-3 bg-purple-600 rounded" onClick={()=>setStarted(false)}>設定へ</button>{state.winner&&<div className="fixed inset-0 bg-black/60 flex items-center justify-center"><div className="bg-slate-800 p-8 rounded-xl text-center"><h2 className="text-3xl">{state.winner===side?'勝利':'敗北'}</h2><button className="mt-4 p-3 bg-purple-600 rounded" onClick={reset}>もう一度</button></div></div>}</main>
}